import { expect, test } from "@playwright/test";
import { useTypedVoice } from "./typed-voice-fixture";

test("live cards, density, motion and page-aware voice work together", async ({ page }, info) => {
  await useTypedVoice(page);
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto("/pipeline");
  await expect(page.getByRole("heading", { level: 1, name: "Pipeline", exact: true })).toBeVisible();
  await expect(page.locator('.board-header-art[data-kind="pipeline"]')).toHaveAttribute("aria-hidden", "true");
  await page.goto("/live");
  await expect(page.locator(".page-title")).not.toContainText("Work in motion");
  await expect(page.locator(".page-title")).not.toContainText("Keep the next milestone clear");
  await expect(page.locator(".page-title time")).toBeVisible();
  await expect(page.locator('.board-header-art[data-kind="delivery"]')).toBeVisible();
  await page.getByRole("button", { name: "Add project", exact: true }).click();
  await page.getByLabel("Project name", { exact: true }).fill("Board experience check");
  await page.getByLabel("Organisation / client", { exact: true }).fill("DEMO · Unassigned Studio");
  await page.getByLabel("Project value (£)").fill("1590");
  await page.getByLabel("Next milestone", { exact: true }).fill("Review the first website draft");
  await page.getByRole("button", { name: "Save project", exact: true }).click();
  const card = page.locator(".live-card").filter({ hasText: "Board experience check" });
  await expect(card).toBeVisible();
  await expect(card.locator("footer")).toHaveCount(0);
  await expect(card.locator(".live-card-open p")).toHaveCSS("background-color", "rgba(0, 0, 0, 0)");
  await expect(card.locator(".live-card-open p")).toHaveCSS("padding", "0px");
  const comfortableHeight = (await card.boundingBox())!.height;
  const column = page.getByRole("region", { name: "Kickoff", exact: true });
  const initialWidth = (await column.boundingBox())!.width;
  const density = page.getByRole("group", { name: "Live project card density" });
  await density.getByRole("button", { name: "Compact", exact: true }).click();
  await expect(density.getByRole("button", { name: "Compact", exact: true })).toHaveAttribute("aria-pressed", "true");
  await expect(page.locator(".live-board-viewport")).toHaveAttribute("data-density", "compact");
  expect((await card.boundingBox())!.height).toBeLessThan(comfortableHeight);
  await expect(card).toContainText("£1,590.00");
  await expect(card).toContainText("Review the first website draft");
  await density.getByRole("button", { name: "Comfortable", exact: true }).click();
  await expect.poll(async () => Math.round((await column.boundingBox())!.width)).toBe(Math.round(initialWidth));
  await expect(column).toHaveCSS("transition-property", "flex-basis");
  await column.getByRole("button", { name: "Expand Kickoff to three lanes" }).click();
  await expect.poll(async () => (await column.boundingBox())!.width).toBeGreaterThan(initialWidth * 2);
  await column.getByRole("button", { name: "Collapse Kickoff to one lane" }).click();
  await expect.poll(async () => Math.round((await column.boundingBox())!.width)).toBe(Math.round(initialWidth));
  await expect.poll(async () => (await column.boundingBox())!.x).toBeGreaterThanOrEqual((await page.locator(".live-board-viewport").boundingBox())!.x);
  await page.emulateMedia({ reducedMotion: "reduce" });
  expect(await column.evaluate((element) => parseFloat(getComputedStyle(element).transitionDuration))).toBeLessThan(0.001);
  await page.emulateMedia({ reducedMotion: "no-preference" });
  await page.screenshot({ path: info.outputPath("live-comfortable.png"), animations: "disabled" });

  await page.getByRole("button", { name: "Talk to GUD", exact: true }).click();
  const voice = page.locator(".workspace-voice-dialog");
  const scope = voice.getByRole("group", { name: "Voice record scope" });
  await expect(scope.getByRole("button", { name: "Live projects", exact: true })).toHaveAttribute("aria-pressed", "true");
  expect(await voice.locator(".voice-record-list em").allTextContents()).not.toContain("Sales");
  await expect(voice.getByLabel("Your update", { exact: true })).toHaveAttribute("placeholder", /next milestone/);
  await voice.getByLabel("Find a voice record").fill("no matching client at all");
  await expect(voice.getByText(/No matching records/)).toBeVisible();
  await voice.getByRole("button", { name: "Close voice workspace" }).click();

  await card.getByRole("button", { name: "Update DEMO · Unassigned Studio project by voice or text" }).click();
  await expect(voice.locator(".voice-selected")).toContainText("DEMO · Unassigned Studio");
  await expect(voice.locator(".voice-selected")).toContainText("Live project");
  await voice.getByLabel("Your update", { exact: true }).fill("Keep this delivery draft on its original record.");
  await voice.getByRole("button", { name: "Close voice workspace" }).click();
  await page.goto("/pipeline");
  await page.getByRole("button", { name: "Talk to GUD", exact: true }).click();
  await expect(voice.locator(".voice-selected")).toContainText("DEMO · Unassigned Studio");
  await expect(voice.getByText(/Resuming your saved live project draft/)).toBeVisible();
  await voice.getByRole("button", { name: "Discard words", exact: true }).click();
  await expect(scope.getByRole("button", { name: "Pipeline", exact: true })).toHaveAttribute("aria-pressed", "true");
  expect(await voice.locator(".voice-record-list em").allTextContents()).not.toContain("Live project");
  await scope.getByRole("button", { name: "All records", exact: true }).click();
  await expect(voice.getByRole("button", { name: /DEMO · Unassigned Studio Board experience check Live project/ })).toBeVisible();
  await voice.getByRole("button", { name: "Close voice workspace" }).click();

  await page.goto("/my-work");
  await expect(page.getByRole("heading", { name: "Pipeline", level: 2, exact: true })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Live projects", level: 2, exact: true })).toBeVisible();
  await page.screenshot({ path: info.outputPath("today-sections.png"), animations: "disabled" });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto("/live");
  await density.getByRole("button", { name: "Compact", exact: true }).click();
  await expect(density).toBeInViewport();
  expect((await page.getByRole("region", { name: "Live project filters" }).boundingBox())!.height).toBeLessThan(200);
  await expect(page.getByRole("button", { name: "Add project", exact: true })).toBeInViewport();
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(391);
  await page.screenshot({ path: info.outputPath("live-compact-mobile.png"), animations: "disabled" });
});
