import { expect, test } from "@playwright/test";

test("saves delivery value independently, preserves zero, and allows clearing", async ({ page }, testInfo) => {
  const hydrationErrors: string[] = [];
  page.on("console", (message) => { if (/hydrat/i.test(message.text())) hydrationErrors.push(message.text()); });
  await page.goto("/live");
  await page.getByRole("button", { name: "Add project", exact: true }).click();
  await page.getByLabel("Project name", { exact: true }).fill("Agreed delivery value test");
  await page.getByLabel("Organisation / client", { exact: true }).fill("DEMO · Value Studio");
  const value = page.getByLabel("Project value (£)", { exact: true });
  await expect(value).toHaveValue("");
  await value.fill("-5");
  await page.getByRole("button", { name: "Save project", exact: true }).click();
  await expect(page.getByRole("dialog")).toBeVisible();
  expect(await value.evaluate((input: HTMLInputElement) => input.validity.rangeUnderflow)).toBeTruthy();
  await value.fill("12500.25");
  await page.screenshot({ path: testInfo.outputPath("project-value-desktop.png"), animations: "disabled" });
  await page.getByRole("button", { name: "Save project", exact: true }).click();
  const card = page.locator(".live-card-open").filter({ hasText: "Agreed delivery value test" });
  await expect(card).toContainText("£12,500.25");
  await page.reload();
  await card.click();
  await expect(value).toHaveValue("12500.25");
  await value.fill("42");
  await page.getByRole("button", { name: "Close project", exact: true }).click();
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await card.click();
  await expect(value).toHaveValue("12500.25");
  await value.fill("0");
  await page.getByRole("button", { name: "Save project", exact: true }).click();
  await expect(card).toContainText("£0.00");
  await page.reload();
  await card.click();
  await expect(value).toHaveValue("0");
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(value).toBeVisible();
  await value.scrollIntoViewIfNeeded();
  await page.screenshot({ path: testInfo.outputPath("project-value-mobile.png"), animations: "disabled" });
  await value.fill("");
  await page.getByRole("button", { name: "Save project", exact: true }).click();
  await expect(card.locator(".live-card-value")).toHaveCount(0);
  await page.reload();
  await card.click();
  await expect(value).toHaveValue("");
  expect(hydrationErrors).toEqual([]);
});
