import { expect, test } from "@playwright/test";
import { useTypedVoice } from "./typed-voice-fixture";

test("simpler editing, formatting, voice draft, direction and archive", async ({ page }, info) => {
  await useTypedVoice(page);
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto("/thoughts");
  await expect(page.getByRole("link", { name: "Marketing Ideas", exact: true })).toBeVisible();
  await expect(page.locator(".thoughts-header")).not.toContainText("A little room");
  await page.getByLabel("New thought", { exact: true }).fill("Refinement fixture");
  await page.getByRole("button", { name: "Add thought", exact: true }).click();
  const note = page.locator(".thought-note").filter({ hasText: "Refinement fixture" });
  await expect(note.locator(".thought-note-category")).toHaveCount(0);
  await expect(page.getByRole("link", { name: "Thoughts", exact: true }).locator("svg")).toHaveClass(/lucide-thought-bubble/);
  await note.getByRole("button", { name: /^Voice edit thought/ }).click();
  const dialog = page.getByRole("dialog");
  await expect(dialog.getByRole("heading", { name: "Edit thought", exact: true })).toHaveClass("sr-only");
  await dialog.getByLabel("Voice draft text", { exact: true }).fill("Add an extra observation");
  await dialog.getByRole("button", { name: "Apply to draft" }).click();
  await expect(dialog.getByLabel("Thought", { exact: true })).toContainText("Add an extra observation");
  const body = dialog.getByLabel("Thought", { exact: true });
  await body.fill("Refinement fixture");
  await body.press("ControlOrMeta+a");
  await dialog.getByRole("button", { name: "Bold", exact: true }).click();
  await expect(body).toHaveValue("**Refinement fixture**");
  await expect(dialog.getByLabel("Formatted preview").locator("strong")).toHaveText("Refinement fixture");
  await body.press("End");
  await dialog.getByRole("button", { name: "Add link", exact: true }).click();
  await dialog.getByLabel("Link URL").fill("javascript:alert(1)");
  await dialog.getByRole("button", { name: "Insert link" }).click();
  await expect(dialog.getByRole("alert")).toContainText("valid http");
  await dialog.getByLabel("Link URL").fill("https://example.com");
  await dialog.getByRole("button", { name: "Insert link" }).click();
  await expect(dialog.getByLabel("Formatted preview").getByRole("link")).toHaveAttribute("href", "https://example.com/");
  await expect(dialog.getByText("List", { exact: true })).toBeVisible();
  await dialog.getByLabel("Title", { exact: true }).fill("Title comes first");
  await dialog.getByLabel("Find or create category", { exact: true }).fill("Video content");
  await dialog.getByRole("button", { name: "Create “Video content”", exact: true }).click();
  await page.screenshot({ path: info.outputPath("thought-editor.png") });
  await dialog.getByRole("button", { name: "Save thought", exact: true }).click();
  await expect(note.locator(".thought-note-open strong")).toHaveText("Refinement fixture");
  await expect(note.locator(".thought-note-open > :first-child")).toHaveText("Title comes first");
  await expect(note.locator(".thought-note-open > :nth-child(2)")).toHaveText("Video content");
  const titleBox = await note.getByRole("heading", { name: "Title comes first" }).boundingBox();
  const categoryBox = await note.locator(".thought-note-category").boundingBox();
  const micBox = await note.getByRole("button", { name: /^Voice edit thought/ }).boundingBox();
  expect(categoryBox!.y).toBeGreaterThan(titleBox!.y);
  expect(Math.abs(micBox!.y - titleBox!.y)).toBeLessThan(8);
  await note.getByRole("button", { name: "Explore this idea" }).click();
  const panel = page.getByLabel("Private explorations", { exact: true });
  await panel.getByRole("button", { name: "Speak exploration direction" }).click();
  await panel.getByLabel("Voice draft text", { exact: true }).fill("Compare a small and large experiment");
  await panel.getByRole("button", { name: "Apply to draft" }).click();
  await panel.getByRole("button", { name: "Create thinking outline · no AI" }).click();
  await expect(panel.locator(".thought-document")).toContainText("Compare a small and large experiment");
  await panel.getByRole("button", { name: "Archive thought", exact: true }).click();
  await expect(note).toHaveCount(0);
  await expect(panel.locator(".thought-document")).toBeVisible();
  await panel.getByRole("button", { name: "Restore thought", exact: true }).click();
  await expect(note).toBeVisible();
  await page.screenshot({ path: info.outputPath("thought-board.png") });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: info.outputPath("thought-mobile.png") });
});
