import { expect, test } from "@playwright/test";

test("private capture, dragging, checklist, colour and exploration history", async ({ page }, info) => {
  await page.setViewportSize({ width: 1440, height: 1050 });
  await page.goto("/thoughts");
  await expect(page.getByRole("heading", { name: "Thoughts", exact: true })).toBeVisible();
  await page.getByLabel("New thought", { exact: true }).fill("Maybe a tiny community studio");
  await page.getByLabel("New thought", { exact: true }).press("Enter");
  const note = page.locator(".thought-note").filter({ hasText: "Maybe a tiny community studio" });
  await expect(note).toBeVisible();
  await note.getByRole("button", { name: /^Edit thought/ }).click();
  const dialog = page.getByRole("dialog");
  await dialog.getByLabel("Title", { exact: false }).fill("Community studio");
  await dialog.getByRole("button", { name: "sage note" }).click();
  await dialog.getByLabel("Add a checklist item").fill("Ask three neighbours");
  await dialog.getByLabel("Add a checklist item").press("Enter");
  await dialog.getByRole("button", { name: "Save thought", exact: true }).click();
  await expect(dialog).toHaveCount(0);
  await expect(note).toHaveAttribute("data-colour", "sage");
  await note.getByRole("button", { name: "Ask three neighbours" }).click();
  await expect(note.getByRole("button", { name: "Ask three neighbours" })).toHaveAttribute("aria-pressed", "true");
  await expect(page.getByRole("status").filter({ hasText: "Thought saved privately" })).toBeVisible();
  const before = await note.boundingBox();
  const grip = note.getByRole("button", { name: /^Move thought/ });
  const box = (await grip.boundingBox())!;
  await page.mouse.move(box.x + 8, box.y + 8); await page.mouse.down(); await page.mouse.move(box.x + 368, box.y + 130, { steps: 20 }); await page.mouse.up();
  await expect.poll(async () => (await note.boundingBox())!.x).toBeGreaterThan(before!.x + 300);
  await page.reload();
  await expect.poll(async () => (await note.boundingBox())!.x).toBeGreaterThan(before!.x + 300);
  await page.getByRole("button", { name: "Compact", exact: true }).click();
  expect((await note.boundingBox())!.width).toBe(220);
  await page.reload();
  await expect(page.getByRole("button", { name: "Compact", exact: true })).toHaveAttribute("aria-pressed", "true");
  await page.getByRole("button", { name: "Comfortable", exact: true }).click();
  await note.getByRole("button", { name: "Explore this idea" }).click();
  const panel = page.getByLabel("Private explorations", { exact: true });
  await panel.getByRole("button", { name: "Create thinking outline · no AI" }).click();
  await expect(panel.locator(".thought-document")).toContainText("Thinking template · not AI research");
  await panel.getByRole("button", { name: "Create thinking outline · no AI" }).click();
  await expect(panel.locator("select option")).toHaveCount(2);
  await expect(note.locator(".thought-note-open")).not.toContainText("Research to do");
  await panel.getByRole("button", { name: "Pull out exploration panel" }).click();
  await expect(panel).toHaveAttribute("data-wide", "true");
  await panel.getByRole("button", { name: "All ideas" }).click();
  await expect(panel.getByRole("heading", { name: "All explorations" })).toBeVisible();
  await expect(panel).toHaveAttribute("data-wide", "true");
  await page.screenshot({ path: info.outputPath("thoughts-exploration.png") });
  await panel.getByRole("button", { name: "Close explorations" }).click();
  await page.screenshot({ path: info.outputPath("thoughts-board.png") });
  await page.getByRole("button", { name: "Talk to GUD", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Talk through a thought" })).toBeVisible();
  await page.getByLabel("Your words").fill("Gud, new thought: Try a weekend workshop. To do: invite a friend. Explore that");
  await page.getByRole("button", { name: "Save thought", exact: true }).click();
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await expect(panel).toContainText("Try a weekend workshop");
  await panel.getByRole("button", { name: "Close explorations" }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.locator(".thoughts-capture")).toBeVisible();
  await page.screenshot({ path: info.outputPath("thoughts-mobile.png") });
});
