import type { EditionDefinition } from "@/lib/editions/types";

export const serviceEdition: EditionDefinition = {
  key: "service",
  name: "Service Sales",
  shortName: "Service",
  audience: "Consultancies, agencies and independent specialists",
  description: "A calm, flexible sales workspace for project work, retainers, consultancy and other professional services.",
  pipelineName: "Service Sales",
  defaultOffer: {
    id: "91000000-0000-4000-8000-000000000001",
    name: "Primary service",
    colour: "#6554C0",
    description: "The main service this workspace is currently selling.",
    idealCustomer: "An organisation with a clear problem, credible budget and an owner for the decision.",
    positioning: "A focused service shaped around the client's actual outcome, not a generic package.",
    isDefault: true,
    active: true,
    position: 0,
  },
  stageNames: [
    "Researching",
    "Research holding",
    "Ready to contact",
    "Outreach active",
    "Conversation active",
    "Discovery booked",
    "Proposal sent",
    "Decision pending",
    "Nurture",
    "Won",
    "Lost",
  ],
  language: {
    company: "organisation",
    companies: "organisations",
    contact: "person",
    contacts: "people",
    opportunity: "opportunity",
    opportunities: "opportunities",
    offer: "service",
    offers: "services",
    handoff: "client handoff",
  },
};
